---
openapi: "3.0.0"
info:
  contact:
    email: "gegevensmagazijn@duo.nl"
    name: "Dienst Uitvoering Onderwijs"
    url: "https://www.duo.nl"
  title: "DUO Catalogus API"
  version: "1.0.0"
  description: >
    Voor ontwikkelaars die de data uit RIO in een eigen applicatie 
    willen inzetten  is de catalogus met RIO-metadata gevirtualiseerd 
    met een API.  Dit heeft als doel perfecte traceerbaarheid van 
    gegevens door verschillende omgevingen in een ketenproces heen. 
    Met deze API kunnen de gewenste gegevensbeschrijvingen worden 
    opgezocht en de URI worden vastgelegd in lokale 
    systemen/documentatie.  Hierdoor blijven de definities scherp en 
    de terminologie eenduidig. Ook kunnen de consequenties van 
    veranderingen aan de bron makkelijker worden uitgezocht.
    Nota bene 1:  Het is aantrekkelijk als aanbieders van data hun 
    metadata volgens een collectief profiel als dit ontsluiten. DUO, 
    als afnemer van de basisregistraties, zou op deze manier een link 
    kunnen opnemen van BPR- of andere gegevens in applicatie-ontwerpen.
    Nota bene 2: In de praktijk maken organisaties een eigen keuze uit 
    een scala van (commerci&#235;le)  ontwikkelplatforms. Het idee achter de 
    catalogus-API is vooral krachtig als zulke platforms in staat zijn 
    om de API uit te vragen.
servers:
- url: "https://lod.onderwijsregistratie.nl/api/catalogus/v1"
paths:
  /concept:
    get:
      parameters:
      - $ref: "#/components/parameters/subjectConcept"
      responses:
        200:
          $ref: "#/components/responses/Concept"
        401:
          $ref: "#/components/responses/401"
        403:
          $ref: "#/components/responses/403"
        404:
          $ref: "#/components/responses/404"
        406:
          $ref: "#/components/responses/406"
        503:
          $ref: "#/components/responses/503"
      summary: "Concept resource"
  /concepten:
    get:
      parameters:
      - $ref: "#/components/parameters/page"
      - $ref: "#/components/parameters/pageSize"
      - $ref: "#/components/parameters/schema"
      - $ref: "#/components/parameters/klasse"
      - $ref: "#/components/parameters/eigenschap"
      - $ref: "#/components/parameters/filter"
      - $ref: "#/components/parameters/sortPropertyConcept"
      - $ref: "#/components/parameters/sortDirection"
      responses:
        200:
          $ref: "#/components/responses/Concepten"
        401:
          $ref: "#/components/responses/401"
        403:
          $ref: "#/components/responses/403"
        406:
          $ref: "#/components/responses/406"
        503:
          $ref: "#/components/responses/503"
      summary: "Concepten collectie"
  /eigenschap:
    get:
      parameters:
      - $ref: "#/components/parameters/subjectEigenschap"
      responses:
        200:
          $ref: "#/components/responses/Eigenschap"
        401:
          $ref: "#/components/responses/401"
        403:
          $ref: "#/components/responses/403"
        404:
          $ref: "#/components/responses/404"
        406:
          $ref: "#/components/responses/406"
        503:
          $ref: "#/components/responses/503"
      summary: "Eigenschap resource"
  /eigenschappen:
    get:
      parameters:
      - $ref: "#/components/parameters/page"
      - $ref: "#/components/parameters/pageSize"
      - $ref: "#/components/parameters/concept"
      - $ref: "#/components/parameters/klasse"
      - $ref: "#/components/parameters/model"
      - $ref: "#/components/parameters/filter"
      - $ref: "#/components/parameters/sortProperty"
      - $ref: "#/components/parameters/sortDirection"
      responses:
        200:
          $ref: "#/components/responses/Eigenschappen"
        401:
          $ref: "#/components/responses/401"
        403:
          $ref: "#/components/responses/403"
        406:
          $ref: "#/components/responses/406"
        503:
          $ref: "#/components/responses/503"
      summary: "Eigenschappen collectie"
  /klasse:
    get:
      parameters:
      - $ref: "#/components/parameters/subjectKlasse"
      responses:
        200:
          $ref: "#/components/responses/Klasse"
        401:
          $ref: "#/components/responses/401"
        403:
          $ref: "#/components/responses/403"
        404:
          $ref: "#/components/responses/404"
        406:
          $ref: "#/components/responses/406"
        503:
          $ref: "#/components/responses/503"
      summary: "Klasse resource"
  /klassen:
    get:
      parameters:
      - $ref: "#/components/parameters/page"
      - $ref: "#/components/parameters/pageSize"
      - $ref: "#/components/parameters/concept"
      - $ref: "#/components/parameters/eigenschap"
      - $ref: "#/components/parameters/model"
      - $ref: "#/components/parameters/filter"
      - $ref: "#/components/parameters/sortProperty"
      - $ref: "#/components/parameters/sortDirection"
      responses:
        200:
          $ref: "#/components/responses/Klassen"
        401:
          $ref: "#/components/responses/401"
        403:
          $ref: "#/components/responses/403"
        406:
          $ref: "#/components/responses/406"
        503:
          $ref: "#/components/responses/503"
      summary: "Klassen collectie"
  /model:
    get:
      parameters:
      - $ref: "#/components/parameters/subjectModel"
      responses:
        200:
          $ref: "#/components/responses/Model"
        401:
          $ref: "#/components/responses/401"
        403:
          $ref: "#/components/responses/403"
        404:
          $ref: "#/components/responses/404"
        406:
          $ref: "#/components/responses/406"
        503:
          $ref: "#/components/responses/503"
      summary: "Model resource"
  /modellen:
    get:
      parameters:
      - $ref: "#/components/parameters/page"
      - $ref: "#/components/parameters/pageSize"
      - $ref: "#/components/parameters/eigenschap"
      - $ref: "#/components/parameters/klasse"
      - $ref: "#/components/parameters/filter"
      - $ref: "#/components/parameters/sortProperty"
      - $ref: "#/components/parameters/sortDirection"
      responses:
        200:
          $ref: "#/components/responses/Modellen"
        401:
          $ref: "#/components/responses/401"
        403:
          $ref: "#/components/responses/403"
        406:
          $ref: "#/components/responses/406"
        503:
          $ref: "#/components/responses/503"
      summary: "Modellen collectie"
components:
  headers:
    Retry-After:
      description: "Tijdstip waarop verwacht is dat de service weer beschikbaar zal\
        \ zijn."
      schema:
        format: "date-time"
        type: "string"
      x-example: "Sun, 28 Nov 2017 16:41:41 GMT"
    X-Pagination-Limit:
      description: "Aantal Objecten per pagina"
      schema:
        format: "int32"
        type: "integer"
    X-Pagination-Page:
      description: "Nummer van de huidige pagina (paginanummering start bij 1)"
      schema:
        format: "int32"
        type: "integer"
    X-Request-ID:
      description: "ID van het request"
      schema:
        type: "string"
    X-Total-Count:
      description: "Totaal aantal resultaten (max 15.000)"
      schema:
        format: "int32"
        type: "integer"
  parameters:
    concept:
      description: "Filteren op `concept`"
      in: "query"
      name: "concept"
      example: "http://lod.onderwijsregistratie.nl/cat/term/BevoegdGezag"
      schema:
        type: "string"
    eigenschap:
      description: "Filteren op `eigenschap`"
      example: "http://lod.onderwijsregistratie.nl/cat/cdm/def/bevoegdGezagnummer"
      in: "query"
      name: "eigenschap"
      schema:
        type: "string"
    filter:
      description: "Hoofdletter ongevoelig filteren op `labels` van de resource"
      example: "post"
      in: "query"
      name: "filter"
      schema:
        type: "string"
    klasse:
      description: "Filteren op `klasse`"
      example: "http://lod.onderwijsregistratie.nl/cat/cdm/def/BevoegdGezagErkenning"
      in: "query"
      name: "klasse"
      schema:
        type: "string"
    model:
      description: "Filteren op `model`"
      example: "http://lod.onderwijsregistratie.nl/cat/doc/ontology/v1/Cdm"
      in: "query"
      name: "model"
      schema:
        type: "string"
    page:
      description: "Paginanummer voor paginering. Gebruik het `_links.next.href` object\
        \ om te navigeren."
      in: "query"
      name: "page"
      required: false
      schema:
        default: 1
        format: "int32"
        minimum: 1
        type: "integer"
    pageSize:
      in: "query"
      name: "pageSize"
      required: false
      schema:
        default: 20
        enum:
        - 10
        - 20
        - 50
        - 100
        format: "int32"
        type: "integer"
    schema:
      description: "Filteren op `schema`"
      example: "http://lod.onderwijsregistratie.nl/cat/doc/taxonomy/Onderwijswettelijk"
      in: "query"
      name: "schema"
      schema:
        type: "string"
    sortDirection:
      description: "Specificeert de richting van de sortering."
      example: "desc"
      in: "query"
      name: "sortDirection"
      schema:
        default: "asc"
        enum:
        - "asc"
        - "desc"
        type: "string"
    sortProperty:
      description: "Specificeert op welk atribuut gesorteerd moet worden."
      example: "label"
      in: "query"
      name: "sortProperty"
      schema:
        enum:
        - "label"
        type: "string"
    sortPropertyConcept:
      description: "Specificeert op welk atribuut gesorteerd moet worden."
      example: "altLabel"
      in: "query"
      name: "sortProperty"
      schema:
        enum:
        - "label"
        - "altLabel"
        type: "string"
    subjectConcept:
      description: "URI van de op te vragen resource."
      in: "query"
      example: "http://lod.onderwijsregistratie.nl/cat/term/BevoegdGezag"
      name: "subject"
      required: true
      schema:
        type: "string"
    subjectKlasse:
      description: "URI van de op te vragen resource."
      in: "query"
      example: "http://lod.onderwijsregistratie.nl/cat/cdm/def/AangebodenMboOpleiding"
      name: "subject"
      required: true
      schema:
        type: "string"
    subjectEigenschap:
      description: "URI van de op te vragen resource."
      in: "query"
      example: "http://lod.onderwijsregistratie.nl/cat/cdm/sh/Cijfer/cijferExamen"
      name: "subject"
      required: true
      schema:
        type: "string"
    subjectModel:
      description: "URI van de op te vragen resource."
      in: "query"
      example: "http://lod.onderwijsregistratie.nl/cat/doc/ontology/v1/Cdm"
      name: "subject"
      required: true
      schema:
        type: "string"
  responses:
    401:
      content:
        application/hal+json:
          schema:
            $ref: "#/components/schemas/Error"
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Error"
      description: "Unauthorized. Je hebt waarschijnlijk geen geldige `X-Api-Key`\
        \ header meegestuurd."
      headers:
        X-Request-ID:
          $ref: "#/components/headers/X-Request-ID"
    403:
      content:
        application/hal+json:
          schema:
            $ref: "#/components/schemas/Error"
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Error"
      description: "Forbidden. Je hebt geen rechten om deze URL te benaderen."
      headers:
        X-Request-ID:
          $ref: "#/components/headers/X-Request-ID"
    404:
      content:
        application/hal+json:
          schema:
            $ref: "#/components/schemas/Error"
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Error"
      description: "Not found"
      headers:
        X-Request-ID:
          $ref: "#/components/headers/X-Request-ID"
    406:
      content:
        application/hal+json:
          schema:
            $ref: "#/components/schemas/Error"
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Error"
      description: "Not Acceptable. Je hebt waarschijnlijk een gewenst formaat met\
        \ de `Accept` header verstuurd welke niet ondersteund wordt. De API kan momenteel\
        \ alleen `application/hal+json` terugsturen."
      headers:
        X-Request-ID:
          $ref: "#/components/headers/X-Request-ID"
    503:
      content:
        application/hal+json:
          schema:
            $ref: "#/components/schemas/Error"
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Error"
      description: "Service Unavailable. Er vindt mogelijk (gepland) onderhoud of\
        \ een storing plaats."
      headers:
        Retry-After:
          $ref: "#/components/headers/Retry-After"
        X-Request-ID:
          $ref: "#/components/headers/X-Request-ID"
    Concept:
      content:
        application/hal+json:
          schema:
            allOf:
            - $ref: "#/components/schemas/Concept"
            type: "object"
      description: "OK."
    Concepten:
      content:
        application/hal+json:
          schema:
            properties:
              _embedded:
                properties:
                  concepten:
                    items:
                      $ref: "#/components/schemas/Concept"
                    type: "array"
                required:
                - "concepten"
                type: "object"
              _links:
                properties:
                  next:
                    description: "Absolute link naar volgende pagina (niet aanwezig\
                      \ als er geen volgende pagina is)"
                    properties:
                      href:
                        description: "URL van de link"
                        example: "https://data.pdok.nl/api/rce/v1/rijksmonumenten?page=3"
                        format: "uri"
                        type: "string"
                    required:
                    - "href"
                    type: "object"
                  prev:
                    description: "Absolute link naar vorige pagina (niet aanwezig\
                      \ als er geen vorige pagina is)"
                    properties:
                      href:
                        description: "URL van de link"
                        example: "https://data.pdok.nl/api/rce/v1/rijksmonumenten?page=1"
                        format: "uri"
                        type: "string"
                    required:
                    - "href"
                    type: "object"
                  self:
                    description: "Absolute link naar huidige pagina"
                    properties:
                      href:
                        description: "URL van de link"
                        example: "https://data.pdok.nl/api/rce/v1/rijksmonumenten?page=2"
                        format: "uri"
                        type: "string"
                    required:
                    - "href"
                    type: "object"
                required:
                - "self"
                type: "object"
            required:
            - "_embedded"
            - "_links"
            type: "object"
      description: "OK."
      headers:
        X-Pagination-Limit:
          $ref: "#/components/headers/X-Pagination-Limit"
        X-Pagination-Page:
          $ref: "#/components/headers/X-Pagination-Page"
        X-Total-Count:
          $ref: "#/components/headers/X-Total-Count"
    Eigenschap:
      content:
        application/hal+json:
          schema:
            allOf:
            - $ref: "#/components/schemas/Eigenschap"
            type: "object"
          examples:
             wordt aangeboden door:
               value:
                 _links:
                   concepten:
                     href: https://lod-acceptatie.onderwijsregistratie.nl/api/catalogus/v1/concepten?eigenschap=http://lod.onderwijsregistratie.nl/cat/cdm/def/AangebodenOpleiding/wordtaangebodendoor
                   klasseNaar:
                     href: https://lod-acceptatie.onderwijsregistratie.nl/api/catalogus/v1/klasse?subject=http://lod.onderwijsregistratie.nl/cat/cdm/def/Onderwijsaanbieder
                   klasseVan:
                     href: https://lod-acceptatie.onderwijsregistratie.nl/api/catalogus/v1/klasse?subject=http://lod.onderwijsregistratie.nl/cat/cdm/def/AangebodenOpleiding
                   modellen:
                     href: https://lod-acceptatie.onderwijsregistratie.nl/api/catalogus/v1/modellen?eigenschap=http://lod.onderwijsregistratie.nl/cat/cdm/sh/AangebodenOpleiding/wordtaangebodendoor
                   self:
                     href: https://lod-acceptatie.onderwijsregistratie.nl/api/catalogus/v1/eigenschap?subject=http://lod.onderwijsregistratie.nl/cat/cdm/sh/AangebodenOpleiding/wordtaangebodendoor
                 commentaar: 
                 datatype: 
                 label: "wordt aangeboden door"
                 maxCount: 1
                 maxLength: 
                 minCount: 1
                 minLength: 
                 pattern: 
                 uri: http://lod.onderwijsregistratie.nl/cat/cdm/def/AangebodenOpleiding/wordtaangebodendoor
             PeriodeBegindatum:
               value:
                 _links:
                   concepten:
                     href: https://lod-acceptatie.onderwijsregistratie.nl/api/catalogus/v1/concepten?eigenschap=http://lod.onderwijsregistratie.nl/cat/cdm/def/periodeBegindatum-v01
                   klasseNaar:
                     href: 
                   klasseVan:
                     href: https://lod-acceptatie.onderwijsregistratie.nl/api/catalogus/v1/klasse?subject=http://lod.onderwijsregistratie.nl/cat/cdm/def/AanmeldingMboCohort
                   modellen:
                     href: https://lod-acceptatie.onderwijsregistratie.nl/api/catalogus/v1/modellen?eigenschap=http://lod.onderwijsregistratie.nl/cat/cdm/sh/AanmeldingMboCohort/beginAanmeldperiode
                   self:
                     href: https://lod-acceptatie.onderwijsregistratie.nl/api/catalogus/v1/eigenschap?subject=http://lod.onderwijsregistratie.nl/cat/cdm/sh/AanmeldingMboCohort/beginAanmeldperiode
                 commentaar: De datum die het begin van de periode aangeeft (inclusief).
                 datatype: http://www.w3.org/2001/XMLSchema#date
                 label: "PeriodeBegindatum"
                 maxCount: 
                 maxLength: 
                 minCount: 
                 minLength: 
                 pattern: "([0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]))"
                 uri: http://lod.onderwijsregistratie.nl/cat/cdm/def/periodeBegindatum-v01
             CijferExamen:
               value:
                 _links:
                   concepten:
                     href: https://lod-acceptatie.onderwijsregistratie.nl/api/catalogus/v1/concepten?eigenschap=http://lod.onderwijsregistratie.nl/cat/cdm/def/cijferExamen-v02
                   klasseNaar:
                     href: 
                   klasseVan:
                     href: https://lod-acceptatie.onderwijsregistratie.nl/api/catalogus/v1/klasse?subject=http://lod.onderwijsregistratie.nl/cat/cdm/def/Cijfer
                   modellen:
                     href: https://lod-acceptatie.onderwijsregistratie.nl/api/catalogus/v1/modellen?eigenschap=http://lod.onderwijsregistratie.nl/cat/cdm/sh/Cijfer/cijferExamen
                   self:
                     href: https://lod-acceptatie.onderwijsregistratie.nl/api/catalogus/v1/eigenschap?subject=http://lod.onderwijsregistratie.nl/cat/cdm/sh/Cijfer/cijferExamen
                 commentaar: Een kwantitatief beoordelingsresultaat van een examenonderdeel
                 datatype: http://www.w3.org/2001/XMLSchema#integer
                 label: "CijferExamen"
                 maxCount: 1
                 maxLength: 
                 minCount: 1
                 minLength: 
                 pattern: "\\d{0,3}"
                 uri: http://lod.onderwijsregistratie.nl/cat/cdm/def/cijferExamen-v02
      description: "OK."
    Eigenschappen:
      content:
        application/hal+json:
          schema:
            properties:
              _embedded:
                properties:
                  eigenschappen:
                    items:
                      $ref: "#/components/schemas/Eigenschap"
                    type: "array"
                required:
                - "eigenschappen"
                type: "object"
              _links:
                properties:
                  next:
                    description: "Absolute link naar volgende pagina (niet aanwezig\
                      \ als er geen volgende pagina is)"
                    properties:
                      href:
                        description: "URL van de link"
                        example: "https://data.pdok.nl/api/rce/v1/rijksmonumenten?page=3"
                        format: "uri"
                        type: "string"
                    required:
                    - "href"
                    type: "object"
                  prev:
                    description: "Absolute link naar vorige pagina (niet aanwezig\
                      \ als er geen vorige pagina is)"
                    properties:
                      href:
                        description: "URL van de link"
                        example: "https://data.pdok.nl/api/rce/v1/rijksmonumenten?page=1"
                        format: "uri"
                        type: "string"
                    required:
                    - "href"
                    type: "object"
                  self:
                    description: "Absolute link naar huidige pagina"
                    properties:
                      href:
                        description: "URL van de link"
                        example: "https://data.pdok.nl/api/rce/v1/rijksmonumenten?page=2"
                        format: "uri"
                        type: "string"
                    required:
                    - "href"
                    type: "object"
                required:
                - "self"
                type: "object"
            required:
            - "_embedded"
            - "_links"
            type: "object"
      description: "OK."
      headers:
        X-Pagination-Limit:
          $ref: "#/components/headers/X-Pagination-Limit"
        X-Pagination-Page:
          $ref: "#/components/headers/X-Pagination-Page"
        X-Total-Count:
          $ref: "#/components/headers/X-Total-Count"
    Klasse:
      content:
        application/hal+json:
          schema:
            allOf:
            - $ref: "#/components/schemas/Klasse"
            type: "object"
      description: "OK."
    Klassen:
      content:
        application/hal+json:
          schema:
            properties:
              _embedded:
                properties:
                  klassen:
                    items:
                      $ref: "#/components/schemas/Klasse"
                    type: "array"
                required:
                - "klassen"
                type: "object"
              _links:
                properties:
                  next:
                    description: "Absolute link naar volgende pagina (niet aanwezig\
                      \ als er geen volgende pagina is)"
                    properties:
                      href:
                        description: "URL van de link"
                        example: "https://data.pdok.nl/api/rce/v1/rijksmonumenten?page=3"
                        format: "uri"
                        type: "string"
                    required:
                    - "href"
                    type: "object"
                  prev:
                    description: "Absolute link naar vorige pagina (niet aanwezig\
                      \ als er geen vorige pagina is)"
                    properties:
                      href:
                        description: "URL van de link"
                        example: "https://data.pdok.nl/api/rce/v1/rijksmonumenten?page=1"
                        format: "uri"
                        type: "string"
                    required:
                    - "href"
                    type: "object"
                  self:
                    description: "Absolute link naar huidige pagina"
                    properties:
                      href:
                        description: "URL van de link"
                        example: "https://data.pdok.nl/api/rce/v1/rijksmonumenten?page=2"
                        format: "uri"
                        type: "string"
                    required:
                    - "href"
                    type: "object"
                required:
                - "self"
                type: "object"
            required:
            - "_embedded"
            - "_links"
            type: "object"
      description: "OK."
      headers:
        X-Pagination-Limit:
          $ref: "#/components/headers/X-Pagination-Limit"
        X-Pagination-Page:
          $ref: "#/components/headers/X-Pagination-Page"
        X-Total-Count:
          $ref: "#/components/headers/X-Total-Count"
    Model:
      content:
        application/hal+json:
          schema:
            allOf:
            - $ref: "#/components/schemas/Model"
            type: "object"
      description: "OK."
    Modellen:
      content:
        application/hal+json:
          schema:
            properties:
              _embedded:
                properties:
                  modellen:
                    items:
                      $ref: "#/components/schemas/Model"
                    type: "array"
                required:
                - "modellen"
                type: "object"
              _links:
                properties:
                  next:
                    description: "Absolute link naar volgende pagina (niet aanwezig\
                      \ als er geen volgende pagina is)"
                    properties:
                      href:
                        description: "URL van de link"
                        example: "https://data.pdok.nl/api/rce/v1/rijksmonumenten?page=3"
                        format: "uri"
                        type: "string"
                    required:
                    - "href"
                    type: "object"
                  prev:
                    description: "Absolute link naar vorige pagina (niet aanwezig\
                      \ als er geen vorige pagina is)"
                    properties:
                      href:
                        description: "URL van de link"
                        example: "https://data.pdok.nl/api/rce/v1/rijksmonumenten?page=1"
                        format: "uri"
                        type: "string"
                    required:
                    - "href"
                    type: "object"
                  self:
                    description: "Absolute link naar huidige pagina"
                    properties:
                      href:
                        description: "URL van de link"
                        example: "https://data.pdok.nl/api/rce/v1/rijksmonumenten?page=2"
                        format: "uri"
                        type: "string"
                    required:
                    - "href"
                    type: "object"
                required:
                - "self"
                type: "object"
            required:
            - "_embedded"
            - "_links"
            type: "object"
      description: "OK."
      headers:
        X-Pagination-Limit:
          $ref: "#/components/headers/X-Pagination-Limit"
        X-Pagination-Page:
          $ref: "#/components/headers/X-Pagination-Page"
        X-Total-Count:
          $ref: "#/components/headers/X-Total-Count"
  schemas:
    Concept:
      description: >
        Een concept is een "onderwerp van gesprek". Concepten worden uitgewerkt als onderdeel van een conceptueel 
        model en daarbij horen definities, toelichtingen, relaties met andere concepten, wetsartikelen of andere 
        uitleg. Bij elkaar vormen alle concepten een soort "van Dale" van de uitvoering.
      properties:
        _links:
          properties:
            eigenschappen:
              description: "Link naar de eigenschappen die horen bij dit concept"
              properties:
                href:
                  description: "URL van de link"
                  example: "https://lod.onderwijsregistratie.nl/api/catalogus/v1/eigenschappen?concept=http://lod.onderwijsregistratie.nl/cat/term/BevoegdGezag"
                  format: "uri"
                  type: "string"
              required:
              - "href"
              type: "object"
            klassen:
              description: "Link naar klassen die horen bij dit concept"
              properties:
                href:
                  description: "URL van de link"
                  example: "https://lod.onderwijsregistratie.nl/api/catalogus/v1/klassen?concept=http://lod.onderwijsregistratie.nl/cat/term/BevoegdGezag"
                  format: "uri"
                  type: "string"
              required:
              - "href"
              type: "object"
            self:
              description: "Absolute link naar het concept"
              properties:
                href:
                  description: "URL van de link"
                  example: "https://lod.onderwijsregistratie.nl/api/catalogus/v1/concept?subject=http://lod.onderwijsregistratie.nl/cat/term/BevoegdGezag"
                  format: "uri"
                  type: "string"
              required:
              - "href"
              type: "object"
          type: "object"
        bronnen:
          items:
            type: "string"
            example: "http://wetten.overheid.nl/jci1.3:c:BWBR0005537&hoofdstuk=1&titeldeel=1.1&artikel=1:1&z=2017-12-01&g=2017-12-01"
          type: "array"
          description: "http://purl.org/dc/terms/source"
        definitie:
          type: "string"
          description: "http://www.w3.org/2004/02/skos/core#Definition"
          example: "Een orgaan van een rechtspersoon krachtens publiekrecht ingesteld (a-orgaan) of een persoon of college met enig openbaar gezag bekleed (b-orgaan)."
        label:
          type: "string"
          description: "https://www.w3.org/2000/01/rdf-schema#label"
          example: "Bevoegd gezag"
        schemas:
          items:
            type: "string"
            example: "http://lod.onderwijsregistratie.nl/cat/doc/taxonomy/Organisatie"
          type: "array"
          description: "http://www.w3.org/2004/02/skos/core#ConceptScheme"
        uri:
          type: "string"
          description: "URI van het specifieke concept"
          example: "http://lod.onderwijsregistratie.nl/cat/term/BevoegdGezag"
      type: "object"
    Eigenschap:
      properties:
        _links:
          properties:
            concepten:
              description: "Link naar concepten die horen bij deze eigenschap"
              properties:
                href:
                  description: "URL van de link"
                  format: "uri"
                  type: "string"
              required:
              - "href"
              type: "object"
            klasseNaar:
              description: "In het geval dat deze eigenschap de relatie van een Klasse\
                \ (A) met een andere Klasse (B) beschrijft, dan is dit de link naar\
                \ de Klasse (B)"
              properties:
                href:
                  description: "URL van de link"
                  format: "uri"
                  type: "string"
              required:
              - "href"
              type: "object"
            klasseVan:
              description: "Link naar de klasse die deze eigenschap heeft"
              properties:
                href:
                  description: "URL van de link"
                  format: "uri"
                  type: "string"
              required:
              - "href"
              type: "object"
            modellen:
              description: "Link naar modellen die horen bij deze eigenschap"
              properties:
                href:
                  description: "URL van de link"
                  format: "uri"
                  type: "string"
              required:
              - "href"
              type: "object"
            self:
              description: "Link naar deze eigenschap"
              properties:
                href:
                  description: "URL van de link"
                  format: "uri"
                  type: "string"
              required:
              - "href"
              type: "object"
          type: "object"
        commentaar:
          type: "string"
          description: "http://www.w3.org/2000/01/rdf-schema#comment"
        datatype:
          description: "http://www.w3.org/ns/shacl#datatype"
          type: "string"
        label:
          description: "https://www.w3.org/2000/01/rdf-schema#label"
          type: "string"
        maxCount:
          description: "http://www.w3.org/ns/shacl#maxCount"
          type: "integer"
        maxLength:
          description: "http://www.w3.org/ns/shacl#maxLength"
          type: "integer"
        minCount:
          description: "http://www.w3.org/ns/shacl#minCount"
          type: "integer"
        minLength:
          description: "http://www.w3.org/ns/shacl#minLength"
          type: "integer"
        pattern:
          description: "http://www.w3.org/ns/shacl#pattern"
          type: "string"
        uri:
          description: "URI van de specifieke eigenschap"
          type: "string"
      required:
      - "_links"
      type: "object"
    Error:
      description: "Object gespecificeerd volgens https://tools.ietf.org/html/rfc7807."
      properties:
        detail:
          example: "HTTP 404 Not Found"
          type: "string"
        instance:
          example: "self"
          type: "string"
        status:
          example: 404
          format: "int32"
          type: "integer"
        title:
          example: "Not Found"
          type: "string"
        type:
          description: "URI naar een pagina met meer informatie over deze foutmelding\
            \ voor de ontwikkelaar."
          example: "about:blank"
          type: "string"
      required:
      - "title"
      - "status"
      - "detail"
      type: "object"
    Klasse:
      description: >
        Een klasse van gegevens is de type-aanduiding voor een groep van gelijksoortige gegevens.  Het heeft 
        een aantal verplichte of optionele eigenschappen.  De structuur van de groep gegevens ligt daarmee vast. 
        De betekenis en doelstelling van een klasse worden nader uitgelegd aan de hand van een concept. (Noot GGR: 
        klassen kunnen eigenschappen overerven van een superklasse, maar dat is nu niet in de api opgenomen).
        
        Een enumeratieklasse is een speciaal soort klasse met een limitatieve set van toegestane waarden. 
        Enumeratieklassen worden centraal beheerd en meervoudig gebruikt in logische modellen.  Wat wordt bedoeld 
        met een enumatieklasse wordt nader uitgelegd aan de hand van een concept.
      properties:
        _links:
          properties:
            concepten:
              description: "Link naar concepten die horen bij deze eigenschap"
              properties:
                href:
                  description: "URL van de link"
                  example: "https://lod.onderwijsregistratie.nl/api/catalogus/v1/concepten?klasse=http://lod.onderwijsregistratie.nl/cat/cdm/def/AangebodenMboOpleiding"
                  format: "uri"
                  type: "string"
              required:
              - "href"
              type: "object"
            eigenschappen:
              description: "Link naar de eigenschappen die horen bij deze klasse"
              properties:
                href:
                  description: "URL van de link"
                  example: "https://lod.onderwijsregistratie.nl/api/catalogus/v1/eigenschappen?klasse=http://lod.onderwijsregistratie.nl/cat/cdm/def/AangebodenMboOpleiding"
                  format: "uri"
                  type: "string"
              required:
              - "href"
              type: "object"
            modellen:
              description: "Link naar modellen die horen bij deze eigenschap"
              properties:
                href:
                  description: "URL van de link"
                  example: "https://lod.onderwijsregistratie.nl/api/catalogus/v1/modellen?klasse=http://lod.onderwijsregistratie.nl/cat/cdm/def/AangebodenMboOpleiding"
                  format: "uri"
                  type: "string"
              required:
              - "href"
              type: "object"
            self:
              description: "Absolute link naar de resource"
              properties:
                href:
                  description: "URL van de link"
                  example: "https://lod.onderwijsregistratie.nl/api/catalogus/v1/klasse?subject=http://lod.onderwijsregistratie.nl/cat/cdm/def/AangebodenMboOpleiding"
                  format: "uri"
                  type: "string"
              required:
              - "href"
              type: "object"
          type: "object"
        commentaar:
          type: "string"
          description: "https://www.w3.org/2000/01/rdf-schema#comment"
          example: "Is een Opleidingseenheid die door een Onderwijsaanbieder aangeboden wordt in het MBO, in een bepaalde vorm, al dan niet op een bepaalde Onderwijslocatie."
        enumeratie:
          items:
            properties:
              code:
                type: "string"
                description: "URI van een voorkomen in de limitatieve set van toegestane waarden."
              label:
                type: "string"
                description: "https://www.w3.org/2000/01/rdf-schema#label"
            type: "object"
          type: "array"
        label:
          type: "string"
          description: "https://www.w3.org/2000/01/rdf-schema#label"
          example: "AangebodenMboOpleiding"
        uri:
          type: "string"
          description: "URI van de specifieke klasse"
          example: "http://lod.onderwijsregistratie.nl/cat/cdm/def/AangebodenMboOpleiding"
        vervangenDoor:
          nullable: true
          type: "string"
          description: "http://purl.org/dc/terms/isReplacedBy"
          example: "http://lod.onderwijsregistratie.nl/cat/cdm/def/NieuweKlasse"
      required:
      - "_links"
      type: "object"
    Model:
      description: >
        https://www.w3.org/2002/07/owl#Ontology: Logische data-/informatiemodellen worden in de ontwerpfase gemaakt om een set gegevens voor uitwisseling 
        en/of opslag functioneel te beschrijven .  Modellen bestaan uit klassen, associaties, eigenschappen en 
        enumeraties.  In samenhang kunnen ze dienen om de integriteit van de beschreven data te valideren. 
        Technische modellen  worden afgeleid van de logische modellen maar zijn vaak specifiek voor gebruikte 
        techniek.
      properties:
        _links:
          properties:
            eigenschappen:
              description: "Link naar eigenschappen die horen bij dit model"
              properties:
                href:
                  description: "URL van de link"
                  example: "https://lod.onderwijsregistratie.nl/api/catalogus/v1/eigenschappen?model=http://lod.onderwijsregistratie.nl/cat/doc/ontology/v1/Cdm"
                  format: "uri"
                  type: "string"
              required:
              - "href"
              type: "object"
            klassen:
              description: "Link naar klassen die horen bij dit model"
              properties:
                href:
                  description: "URL van de link"
                  example: "https://lod.onderwijsregistratie.nl/api/catalogus/v1/klassen?model=http://lod.onderwijsregistratie.nl/cat/doc/ontology/v1/Cdm"
                  format: "uri"
                  type: "string"
              required:
              - "href"
              type: "object"
            self:
              description: "Link naar dit model"
              properties:
                href:
                  description: "URL van de link"
                  example: "https://lod.onderwijsregistratie.nl/api/catalogus/v1/model?subject=http://lod.onderwijsregistratie.nl/cat/doc/ontology/v1/Cdm"
                  format: "url"
                  type: "string"
              required:
              - "href"
              type: "object"
          type: "object"
        datumVanaf:
          format: "date"
          type: "string"
          example: "2019-01-24"
          description: "http://purl.org/dc/terms/modified"
        label:
          type: "string"
          example: "Canoniek Datamodel DUO"
          description: "https://www.w3.org/2000/01/rdf-schema#label"
        uri:
          type: "string"
          example: "http://lod.onderwijsregistratie.nl/cat/doc/ontology/v1/Cdm"
          description: "URI van het specifieke model"
        versieInfo:
          items:
            type: "string"
            example: "Aangemaakt op 2019-01-24 09:11:24 op basis van commit 3715."
            description: "https://www.w3.org/2002/07/owl#versionInfo"
          type: "array"
      type: "object"
